name: cucumber_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/lamkr/cucumber-dart/cucumber-core

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
